services:
  streamlit-app:
    build: .
    ports:
      - "${PORT:-8501}:${PORT:-8501}"
    network_mode: host
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
      # - ${DOWNLOAD_PATH:-./downloads}:${DOWNLOAD_PATH:-./downloads}
      - ${DOWNLOAD_PATH}:${DOWNLOAD_PATH}
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${PORT}
    restart: unless-stopped
